In [11]:
import pandas as pd

spam_messages = [
    "Win a free iPhone",
    "Claim your cash prize",
    "Get free recharge now",
    "Exclusive offer click here",
    "You won 10000 rupees"
]

ham_messages = [
    "Meeting at 10 AM",
    "Assignment submitted",
    "Class starts at 9 AM",
    "Project deadline today",
    "Notes shared in classroom"
]

texts = []
labels = []

for i in range(20):
    for msg in spam_messages:
        texts.append(msg + " " + str(i))
        labels.append("spam")

    for msg in ham_messages:
        texts.append(msg + " " + str(i))
        labels.append("ham")

df = pd.DataFrame({
    "text": texts,
    "label": labels
})

print(df.shape)
df.head()

(200, 2)

                           text label
0           Win a free iPhone 0  spam
1       Claim your cash prize 0  spam
2       Get free recharge now 0  spam
3  Exclusive offer click here 0  spam
4        You won 10000 rupees 0  spam

In [12]:
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

df.head()

                           text  label
0           Win a free iPhone 0      1
1       Claim your cash prize 0      1
2       Get free recharge now 0      1
3  Exclusive offer click here 0      1
4        You won 10000 rupees 0      1

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts(df['text'])

X = tokenizer.texts_to_sequences(df['text'])

print(X)

[[6, 7, 1, 8, 36], [9, 10, 11, 12, 36], [13, 1, 14, 15, 36], [16, 17, 18, 19, 36], [20, 21, 22, 23, 36], [24, 2, 4, 3, 36], [25, 26, 36], [27, 28, 2, 5, 3, 36], [29, 30, 31, 36], [32, 33, 34, 35, 36], [6, 7, 1, 8, 37], [9, 10, 11, 12, 37], [13, 1, 14, 15, 37], [16, 17, 18, 19, 37], [20, 21, 22, 23, 37], [24, 2, 4, 3, 37], [25, 26, 37], [27, 28, 2, 5, 3, 37], [29, 30, 31, 37], [32, 33, 34, 35, 37], [6, 7, 1, 8, 38], [9, 10, 11, 12, 38], [13, 1, 14, 15, 38], [16, 17, 18, 19, 38], [20, 21, 22, 23, 38], [24, 2, 4, 3, 38], [25, 26, 38], [27, 28, 2, 5, 3, 38], [29, 30, 31, 38], [32, 33, 34, 35, 38], [6, 7, 1, 8, 39], [9, 10, 11, 12, 39], [13, 1, 14, 15, 39], [16, 17, 18, 19, 39], [20, 21, 22, 23, 39], [24, 2, 4, 3, 39], [25, 26, 39], [27, 28, 2, 5, 3, 39], [29, 30, 31, 39], [32, 33, 34, 35, 39], [6, 7, 1, 8, 40], [9, 10, 11, 12, 40], [13, 1, 14, 15, 40], [16, 17, 18, 19, 40], [20, 21, 22, 23, 40], [24, 2, 4, 3, 40], [25, 26, 40], [27, 28, 2, 5, 3, 40], [29, 30, 31, 40], [32, 33, 34, 35, 40], [6, 7, 1, 8, 41], [9, 10, 11, 12, 41], [13, 1, 14, 15, 41], [16, 17, 18, 19, 41], [20, 21, 22, 23, 41], [24, 2, 4, 3, 41], [25, 26, 41], [27, 28, 2, 5, 3, 41], [29, 30, 31, 41], [32, 33, 34, 35, 41], [6, 7, 1, 8, 42], [9, 10, 11, 12, 42], [13, 1, 14, 15, 42], [16, 17, 18, 19, 42], [20, 21, 22, 23, 42], [24, 2, 4, 3, 42], [25, 26, 42], [27, 28, 2, 5, 3, 42], [29, 30, 31, 42], [32, 33, 34, 35, 42], [6, 7, 1, 8, 43], [9, 10, 11, 12, 43], [13, 1, 14, 15, 43], [16, 17, 18, 19, 43], [20, 21, 22, 23, 43], [24, 2, 4, 3, 43], [25, 26, 43], [27, 28, 2, 5, 3, 43], [29, 30, 31, 43], [32, 33, 34, 35, 43], [6, 7, 1, 8, 44], [9, 10, 11, 12, 44], [13, 1, 14, 15, 44], [16, 17, 18, 19, 44], [20, 21, 22, 23, 44], [24, 2, 4, 3, 44], [25, 26, 44], [27, 28, 2, 5, 3, 44], [29, 30, 31, 44], [32, 33, 34, 35, 44], [6, 7, 1, 8, 5], [9, 10, 11, 12, 5], [13, 1, 14, 15, 5], [16, 17, 18, 19, 5], [20, 21, 22, 23, 5], [24, 2, 4, 3, 5], [25, 26, 5], [27, 28, 2, 5, 3, 5], [29, 30, 31, 5], [32, 33, 34, 35, 5], [6, 7, 1, 8, 4], [9, 10, 11, 12, 4], [13, 1, 14, 15, 4], [16, 17, 18, 19, 4], [20, 21, 22, 23, 4], [24, 2, 4, 3, 4], [25, 26, 4], [27, 28, 2, 5, 3, 4], [29, 30, 31, 4], [32, 33, 34, 35, 4], [6, 7, 1, 8, 45], [9, 10, 11, 12, 45], [13, 1, 14, 15, 45], [16, 17, 18, 19, 45], [20, 21, 22, 23, 45], [24, 2, 4, 3, 45], [25, 26, 45], [27, 28, 2, 5, 3, 45], [29, 30, 31, 45], [32, 33, 34, 35, 45], [6, 7, 1, 8, 46], [9, 10, 11, 12, 46], [13, 1, 14, 15, 46], [16, 17, 18, 19, 46], [20, 21, 22, 23, 46], [24, 2, 4, 3, 46], [25, 26, 46], [27, 28, 2, 5, 3, 46], [29, 30, 31, 46], [32, 33, 34, 35, 46], [6, 7, 1, 8, 47], [9, 10, 11, 12, 47], [13, 1, 14, 15, 47], [16, 17, 18, 19, 47], [20, 21, 22, 23, 47], [24, 2, 4, 3, 47], [25, 26, 47], [27, 28, 2, 5, 3, 47], [29, 30, 31, 47], [32, 33, 34, 35, 47], [6, 7, 1, 8, 48], [9, 10, 11, 12, 48], [13, 1, 14, 15, 48], [16, 17, 18, 19, 48], [20, 21, 22, 23, 48], [24, 2, 4, 3, 48], [25, 26, 48], [27, 28, 2, 5, 3, 48], [29, 30, 31, 48], [32, 33, 34, 35, 48], [6, 7, 1, 8, 49], [9, 10, 11, 12, 49], [13, 1, 14, 15, 49], [16, 17, 18, 19, 49], [20, 21, 22, 23, 49], [24, 2, 4, 3, 49], [25, 26, 49], [27, 28, 2, 5, 3, 49], [29, 30, 31, 49], [32, 33, 34, 35, 49], [6, 7, 1, 8, 50], [9, 10, 11, 12, 50], [13, 1, 14, 15, 50], [16, 17, 18, 19, 50], [20, 21, 22, 23, 50], [24, 2, 4, 3, 50], [25, 26, 50], [27, 28, 2, 5, 3, 50], [29, 30, 31, 50], [32, 33, 34, 35, 50], [6, 7, 1, 8, 51], [9, 10, 11, 12, 51], [13, 1, 14, 15, 51], [16, 17, 18, 19, 51], [20, 21, 22, 23, 51], [24, 2, 4, 3, 51], [25, 26, 51], [27, 28, 2, 5, 3, 51], [29, 30, 31, 51], [32, 33, 34, 35, 51], [6, 7, 1, 8, 52], [9, 10, 11, 12, 52], [13, 1, 14, 15, 52], [16, 17, 18, 19, 52], [20, 21, 22, 23, 52], [24, 2, 4, 3, 52], [25, 26, 52], [27, 28, 2, 5, 3, 52], [29, 30, 31, 52], [32, 33, 34, 35, 52], [6, 7, 1, 8, 53], [9, 10, 11, 12, 53], [13, 1, 14, 15, 53], [16, 17, 18, 19, 53], [20, 21, 22, 23, 53], [24, 2, 4, 3, 53], [25, 26, 53], [27, 28, 2, 5, 3, 53], [29, 30, 31, 53], [32, 33, 34, 35, 53]]

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(X, maxlen=5)

print(X)

[[ 6  7  1  8 36]
 [ 9 10 11 12 36]
 [13  1 14 15 36]
 [16 17 18 19 36]
 [20 21 22 23 36]
 [24  2  4  3 36]
 [ 0  0 25 26 36]
 [28  2  5  3 36]
 [ 0 29 30 31 36]
 [32 33 34 35 36]
 [ 6  7  1  8 37]
 [ 9 10 11 12 37]
 [13  1 14 15 37]
 [16 17 18 19 37]
 [20 21 22 23 37]
 [24  2  4  3 37]
 [ 0  0 25 26 37]
 [28  2  5  3 37]
 [ 0 29 30 31 37]
 [32 33 34 35 37]
 [ 6  7  1  8 38]
 [ 9 10 11 12 38]
 [13  1 14 15 38]
 [16 17 18 19 38]
 [20 21 22 23 38]
 [24  2  4  3 38]
 [ 0  0 25 26 38]
 [28  2  5  3 38]
 [ 0 29 30 31 38]
 [32 33 34 35 38]
 [ 6  7  1  8 39]
 [ 9 10 11 12 39]
 [13  1 14 15 39]
 [16 17 18 19 39]
 [20 21 22 23 39]
 [24  2  4  3 39]
 [ 0  0 25 26 39]
 [28  2  5  3 39]
 [ 0 29 30 31 39]
 [32 33 34 35 39]
 [ 6  7  1  8 40]
 [ 9 10 11 12 40]
 [13  1 14 15 40]
 [16 17 18 19 40]
 [20 21 22 23 40]
 [24  2  4  3 40]
 [ 0  0 25 26 40]
 [28  2  5  3 40]
 [ 0 29 30 31 40]
 [32 33 34 35 40]
 [ 6  7  1  8 41]
 [ 9 10 11 12 41]
 [13  1 14 15 41]
 [16 17 18 19 41]
 [20 21 22 23 41]
 [24  2  4  3 41]
 [ 0  0 25 26 41]
 [28  2  5  3 41]
 [ 0 29 30 31 41]
 [32 33 34 35 41]
 [ 6  7  1  8 42]
 [ 9 10 11 12 42]
 [13  1 14 15 42]
 [16 17 18 19 42]
 [20 21 22 23 42]
 [24  2  4  3 42]
 [ 0  0 25 26 42]
 [28  2  5  3 42]
 [ 0 29 30 31 42]
 [32 33 34 35 42]
 [ 6  7  1  8 43]
 [ 9 10 11 12 43]
 [13  1 14 15 43]
 [16 17 18 19 43]
 [20 21 22 23 43]
 [24  2  4  3 43]
 [ 0  0 25 26 43]
 [28  2  5  3 43]
 [ 0 29 30 31 43]
 [32 33 34 35 43]
 [ 6  7  1  8 44]
 [ 9 10 11 12 44]
 [13  1 14 15 44]
 [16 17 18 19 44]
 [20 21 22 23 44]
 [24  2  4  3 44]
 [ 0  0 25 26 44]
 [28  2  5  3 44]
 [ 0 29 30 31 44]
 [32 33 34 35 44]
 [ 6  7  1  8  5]
 [ 9 10 11 12  5]
 [13  1 14 15  5]
 [16 17 18 19  5]
 [20 21 22 23  5]
 [24  2  4  3  5]
 [ 0  0 25 26  5]
 [28  2  5  3  5]
 [ 0 29 30 31  5]
 [32 33 34 35  5]
 [ 6  7  1  8  4]
 [ 9 10 11 12  4]
 [13  1 14 15  4]
 [16 17 18 19  4]
 [20 21 22 23  4]
 [24  2  4  3  4]
 [ 0  0 25 26  4]
 [28  2  5  3  4]
 [ 0 29 30 31  4]
 [32 33 34 35  4]
 [ 6  7  1  8 45]
 [ 9 10 11 12 45]
 [13  1 14 15 45]
 [16 17 18 19 45]
 [20 21 22 23 45]
 [24  2  4  3 45]
 [ 0  0 25 26 45]
 [28  2  5  3 45]
 [ 0 29 30 31 45]
 [32 33 34 35 45]
 [ 6  7  1  8 46]
 [ 9 10 11 12 46]
 [13  1 14 15 46]
 [16 17 18 19 46]
 [20 21 22 23 46]
 [24  2  4  3 46]
 [ 0  0 25 26 46]
 [28  2  5  3 46]
 [ 0 29 30 31 46]
 [32 33 34 35 46]
 [ 6  7  1  8 47]
 [ 9 10 11 12 47]
 [13  1 14 15 47]
 [16 17 18 19 47]
 [20 21 22 23 47]
 [24  2  4  3 47]
 [ 0  0 25 26 47]
 [28  2  5  3 47]
 [ 0 29 30 31 47]
 [32 33 34 35 47]
 [ 6  7  1  8 48]
 [ 9 10 11 12 48]
 [13  1 14 15 48]
 [16 17 18 19 48]
 [20 21 22 23 48]
 [24  2  4  3 48]
 [ 0  0 25 26 48]
 [28  2  5  3 48]
 [ 0 29 30 31 48]
 [32 33 34 35 48]
 [ 6  7  1  8 49]
 [ 9 10 11 12 49]
 [13  1 14 15 49]
 [16 17 18 19 49]
 [20 21 22 23 49]
 [24  2  4  3 49]
 [ 0  0 25 26 49]
 [28  2  5  3 49]
 [ 0 29 30 31 49]
 [32 33 34 35 49]
 [ 6  7  1  8 50]
 [ 9 10 11 12 50]
 [13  1 14 15 50]
 [16 17 18 19 50]
 [20 21 22 23 50]
 [24  2  4  3 50]
 [ 0  0 25 26 50]
 [28  2  5  3 50]
 [ 0 29 30 31 50]
 [32 33 34 35 50]
 [ 6  7  1  8 51]
 [ 9 10 11 12 51]
 [13  1 14 15 51]
 [16 17 18 19 51]
 [20 21 22 23 51]
 [24  2  4  3 51]
 [ 0  0 25 26 51]
 [28  2  5  3 51]
 [ 0 29 30 31 51]
 [32 33 34 35 51]
 [ 6  7  1  8 52]
 [ 9 10 11 12 52]
 [13  1 14 15 52]
 [16 17 18 19 52]
 [20 21 22 23 52]
 [24  2  4  3 52]
 [ 0  0 25 26 52]
 [28  2  5  3 52]
 [ 0 29 30 31 52]
 [32 33 34 35 52]
 [ 6  7  1  8 53]
 [ 9 10 11 12 53]
 [13  1 14 15 53]
 [16 17 18 19 53]
 [20 21 22 23 53]
 [24  2  4  3 53]
 [ 0  0 25 26 53]
 [28  2  5  3 53]
 [ 0 29 30 31 53]
 [32 33 34 35 53]]

In [16]:
from sklearn.model_selection import train_test_split

y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

model = Sequential([
    Embedding(input_dim=1000, output_dim=16, input_length=6),
    Flatten(),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.7375 - loss: 0.6789 - val_accuracy: 0.7000 - val_loss: 0.6722
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9312 - loss: 0.6522 - val_accuracy: 0.9500 - val_loss: 0.6509
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9812 - loss: 0.6235 - val_accuracy: 1.0000 - val_loss: 0.6259
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.5900 - val_accuracy: 1.0000 - val_loss: 0.5938
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.5505 - val_accuracy: 1.0000 - val_loss: 0.5562
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.5060 - val_accuracy: 1.0000 - val_loss: 0.5138
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4563 - val_accuracy: 1.0000 - val_loss: 0.4664
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.4023 - val_accuracy: 1.0000 - val_loss: 0.4143
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.3461 - val_accuracy: 1.0000 - val_loss: 0.3606
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.2914 - val_accuracy: 1.0000 - val_loss: 0.3084

In [24]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.3084
Accuracy: 1.0